# This is a basic workflow to help you get started with Actions

name: sast-scan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: sast-scan
        # You may pin to the exact commit or the version.
        # uses: AppThreat/sast-scan-action@4d0f956e6ba3c940a22679fd8fe7cb2e755f3d96
        uses: AppThreat/sast-scan-action@1.0.2
        with:
          # Source directory to scan. Defaults to workspace
          #src: # optional, default is /github/workspace
          # Output directory for the generated reports. Defaults to reports
         # output: "/github/workspace/reports"
          # Project type. Eg: java, python, nodejs,go. Comma separated values allowed.
          type: "depscan"
      - name: ls -l
        run: cd reports;ls -l
      #- name: Upload report
       # uses: github/codeql-action/upload-sarif@v1
      #  with:
       #   sarif_file: reports/1.sarif
          
